Release 21.3.1
-- git fetch;git merge-base --is-ancestor @{upstream} HEAD

-- rm -rf node_modules;npm install
up to date, audited 1 package in 176ms

found 0 vulnerabilities

-- npm outdated

-- npm outdated -g @litejs/cli uglify-js jshint nyc
Package    Current  Wanted  Latest  Location                Depended by
uglify-js   3.13.1  3.13.2  3.13.2  node_modules/uglify-js  lib

-- lj build
# Build @litejs/ui@21.3.1
@litejs/cli 21.3.0
uglify-js 3.13.1
WARNINGS: /home/lauri/code/litejs/ui/test/index.html
 - '/home/lauri/code/litejs/ui/test/min/0.js' not commited?
 - '/home/lauri/code/litejs/ui/test/min/1.js' not commited?
 - '/home/lauri/code/litejs/ui/test/min/2.js' not commited?
 - '/home/lauri/code/litejs/ui/test/min/3.js' not commited?
WARNINGS: /home/lauri/code/litejs/ui/test/min/3.js
 - WARN: Dropping unreachable code [STDIN:620,6]
 - WARN: Dropping unreachable code [STDIN:780,19]
 - WARN: Dropping unused variable Ud [STDIN:692,3]
 - WARN: Dropping unused variable Xd [STDIN:738,5]
WARNINGS: /home/lauri/code/litejs/ui/test/min/2.js
 - WARN: Dropping duplicated definition of variable ha [STDIN:192,6]
 - WARN: Dropping duplicated definition of variable wc [STDIN:500,10]
 - WARN: Dropping duplicated definition of variable de [STDIN:867,7]
 - WARN: Dropping duplicated definition of variable Jf [STDIN:1067,7]
 - WARN: Dropping duplicated definition of variable Di [STDIN:1451,6]
 - WARN: Dropping duplicated definition of variable xj [STDIN:1620,7]
 - WARN: Dropping duplicated definition of variable Cj [STDIN:1661,6]
 - WARN: Dropping duplicated definition of variable dk [STDIN:1779,6]
 - WARN: Dropping duplicated definition of variable ek [STDIN:1782,4]
WARNINGS: /home/lauri/code/litejs/ui/test/min/1.js
 - WARN: Dropping duplicated definition of variable F [STDIN:83,7]
 - WARN: Dropping unreachable code [STDIN:625,13]
 - WARN: Dropping duplicated definition of variable jj [STDIN:1631,8]
 - WARN: Dropping duplicated definition of variable tj [STDIN:1701,6]
 - WARN: Dropping duplicated definition of variable Ik [STDIN:1986,6]

-- lj test --brief
ReferenceError: window is not defined
    at Object.<anonymous> (/home/lauri/code/litejs/ui/test/polyfill.js:38:3)
    at nextCase (/home/lauri/code/litejs/cli/test.js:291:13)
    at Timeout.endCase [as _onTimeout] (/home/lauri/code/litejs/cli/test.js:335:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
  ✘ index.js #10 [0/0]
---
  ✘ index.js #10 [0/0]
ReferenceError: window is not defined
    at Object.<anonymous> (/home/lauri/code/litejs/ui/test/polyfill.js:38:3)
    at nextCase (/home/lauri/code/litejs/cli/test.js:291:13)
    at Timeout.endCase [as _onTimeout] (/home/lauri/code/litejs/cli/test.js:335:23)
    at listOnTimeout (internal/timers.js:554:17)
...
# FAIL  tests 10
# pass  9/10 [15/15] in 1819 ms at 16:29:09